import React, { useEffect, useState } from 'react';
import {
  View, Text, StyleSheet, FlatList, ActivityIndicator,
  TouchableOpacity, Alert,
} from 'react-native';
import { collection, query, where, onSnapshot, orderBy } from 'firebase/firestore';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { auth, db } from '../../../firebase';
import { colors } from '../../theme/colors';
import { Ionicons } from '@expo/vector-icons';

const MyInvoicesScreen = () => {
  const [tenantId, setTenantId] = useState(null);
  const [tenantInfo, setTenantInfo] = useState(null);
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const user = auth.currentUser;
    if (!user) return;
    import('firebase/firestore').then(({ getDocs, collection: col, where: wh, query: qry }) => {
      getDocs(qry(col(db, 'tenants'), wh('email', '==', user.email))).then(snap => {
        if (!snap.empty) {
          const t = { id: snap.docs[0].id, ...snap.docs[0].data() };
          setTenantId(t.id);
          setTenantInfo(t);
          const q = query(collection(db, 'invoices'), where('tenantId', '==', t.id), orderBy('sentAt', 'desc'));
          const unsub = onSnapshot(q, s => {
            setInvoices(s.docs.map(d => ({ id: d.id, ...d.data() })));
            setLoading(false);
          });
          return unsub;
        } else { setLoading(false); }
      });
    });
  }, []);

  const downloadInvoice = async (invoice) => {
    const html = `
      <!DOCTYPE html>
      <html>
      <head><style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #1A1A2E; }
        .logo { color: #1A3C5E; font-size: 24px; font-weight: bold; }
        h2 { color: #1A3C5E; margin-top: 30px; }
        .info-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #DDE3EC; }
        .total { font-size: 22px; font-weight: bold; color: #1A3C5E; margin-top: 20px; }
        .badge { background: #27AE6020; color: #27AE60; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
      </style></head>
      <body>
        <div class="logo">🏢 PropManager</div>
        <h2>INVOICE</h2>
        <div class="info-row"><span>Invoice #</span><span>${invoice.id?.slice(0, 8).toUpperCase()}</span></div>
        <div class="info-row"><span>Tenant</span><span>${tenantInfo?.name}</span></div>
        <div class="info-row"><span>Unit</span><span>${tenantInfo?.unitNumber}</span></div>
        <div class="info-row"><span>Period</span><span>${invoice.month} ${invoice.year}</span></div>
        <div class="info-row"><span>Due Date</span><span>${invoice.dueDate || '5th of month'}</span></div>
        <div class="info-row"><span>Status</span><span class="badge">${invoice.status?.toUpperCase()}</span></div>
        <div class="total">Total: KES ${invoice.amount?.toLocaleString()}</div>
        <p style="margin-top:40px;color:#6B7B8D;font-size:12px">Generated by PropManager • ${new Date().toLocaleDateString()}</p>
      </body></html>
    `;
    try {
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Invoice - ${invoice.month} ${invoice.year}` });
    } catch (err) { Alert.alert('Error', err.message); }
  };

  const statusColor = { paid: colors.success, sent: colors.warning, pending: colors.warning };

  const renderItem = ({ item }) => (
    <View style={styles.card}>
      <View style={styles.cardTop}>
        <View style={styles.icon}>
          <Ionicons name="receipt" size={20} color={colors.primary} />
        </View>
        <View style={styles.info}>
          <Text style={styles.month}>{item.month} {item.year}</Text>
          <Text style={styles.sub}>Due: {item.dueDate || '5th of month'}</Text>
        </View>
        <View style={[styles.badge, { backgroundColor: (statusColor[item.status] || colors.warning) + '20' }]}>
          <Text style={[styles.badgeText, { color: statusColor[item.status] || colors.warning }]}>
            {item.status?.toUpperCase() || 'SENT'}
          </Text>
        </View>
      </View>
      <View style={styles.cardBottom}>
        <Text style={styles.amount}>KES {item.amount?.toLocaleString()}</Text>
        <TouchableOpacity style={styles.downloadBtn} onPress={() => downloadInvoice(item)}>
          <Ionicons name="download-outline" size={16} color={colors.primary} />
          <Text style={styles.downloadText}>Download PDF</Text>
        </TouchableOpacity>
      </View>
    </View>
  );

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>My Invoices</Text>
        <Text style={styles.subtitle}>Your monthly rent invoices</Text>
      </View>
      {loading ? (
        <ActivityIndicator color={colors.primary} style={{ marginTop: 60 }} />
      ) : (
        <FlatList
          data={invoices}
          keyExtractor={i => i.id}
          renderItem={renderItem}
          contentContainerStyle={styles.list}
          ListEmptyComponent={
            <View style={styles.empty}>
              <Ionicons name="receipt-outline" size={60} color={colors.border} />
              <Text style={styles.emptyText}>No invoices yet</Text>
              <Text style={styles.emptySubtext}>Invoices will appear here when your manager sends them</Text>
            </View>
          }
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    backgroundColor: colors.primary, paddingTop: 56, paddingHorizontal: 20, paddingBottom: 24,
    borderBottomLeftRadius: 24, borderBottomRightRadius: 24,
  },
  title: { fontSize: 24, fontWeight: '800', color: colors.white },
  subtitle: { fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 4 },
  list: { padding: 16, paddingBottom: 40 },
  card: { backgroundColor: colors.white, borderRadius: 16, padding: 16, marginBottom: 12, elevation: 3 },
  cardTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  icon: { width: 44, height: 44, borderRadius: 12, backgroundColor: colors.primary + '12', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  info: { flex: 1 },
  month: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  sub: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  badgeText: { fontSize: 10, fontWeight: '700' },
  cardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  amount: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
  downloadBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.primary + '12', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  downloadText: { fontSize: 13, color: colors.primary, fontWeight: '700' },
  empty: { alignItems: 'center', marginTop: 80 },
  emptyText: { fontSize: 16, fontWeight: '700', color: colors.textSecondary, marginTop: 12 },
  emptySubtext: { fontSize: 13, color: colors.textMuted, marginTop: 6, textAlign: 'center', maxWidth: 250 },
});

export default MyInvoicesScreen;
